version: "3.9"
services:
  mono-repo:
    build: .
    container_name: mono-repo
    restart: always
    networks:
      - main-nginx-net
    command: sh -c "go run main.go"
networks:
  main-nginx-net:
    external: true